# Generated by Django 3.0.5 on 2020-04-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0002_auto_20200420_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_inputs',
            name='family_info',
            field=models.FloatField(verbose_name='Informativité familiale'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='family_pertinence',
            field=models.FloatField(verbose_name='Pertinence familiale'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='genetic_risk',
            field=models.FloatField(verbose_name='Risque génétique'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='irm_to_realise',
            field=models.BooleanField(verbose_name='IRM prostatique à réaliser'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='psa_andro_corr',
            field=models.FloatField(verbose_name='PSA corrigé Andropause'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='psa_density',
            field=models.FloatField(verbose_name='PSA densité'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='psa_density_corr',
            field=models.FloatField(verbose_name='PSA densité corrigé'),
        ),
    ]
