# Generated by Django 3.0.5 on 2020-04-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0003_auto_20200420_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person_Inputs',
            new_name='Person_Input',
        ),
    ]
