# Generated by Django 3.0.5 on 2020-04-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_inputs',
            name='apparente_one',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='declared_cancers',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='family_info',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='family_pertinence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='general_pop_risk',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='genetic_risk',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='individual_risk',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='irm_to_realise',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='psa_andro_corr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='psa_density',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_inputs',
            name='psa_density_corr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Quel est votre Age (ans)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='brother_prostate',
            field=models.PositiveSmallIntegerField(verbose_name='Combien de vos fréres ont eu un cancer de la prostate'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='brothers',
            field=models.PositiveSmallIntegerField(verbose_name='Combien avez-vous de fréres '),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='dark_skin',
            field=models.BooleanField(verbose_name='Avez-vous une peau noire (origine africaine ou antillaise)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='father_prostate',
            field=models.BooleanField(verbose_name='Avez-vous un pére qui a eu un cancer de la prostate'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='heat',
            field=models.BooleanField(verbose_name='Avez vous des bouffées de chaleur'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='height',
            field=models.FloatField(verbose_name='Quel est votre Taille (cm)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='low_testosterone',
            field=models.BooleanField(verbose_name='Votre taux sanguin de testostérone biodisponible est il <0,3 ng/ml'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='medicine_cholesterol',
            field=models.BooleanField(verbose_name='Avez-vous un traitement pour réduire votre taux de cholestérol?'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='medicine_erection',
            field=models.BooleanField(verbose_name='Prenez vous un des médicaments pour faciliter les érections?'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='medicine_fin_dist',
            field=models.BooleanField(verbose_name='Prenez vous un des médicaments suivant (Finasteride ou Dutasteride)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='mother_breast',
            field=models.BooleanField(verbose_name='Avez-vous un mère qui a eu un cancer du sein'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='mutation',
            field=models.BooleanField(verbose_name='Avez-vous une mutation qui prédispose aux cancers Sein (BRCA1 ou BRCA2, Autres)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='older_brothers',
            field=models.PositiveSmallIntegerField(verbose_name='Combien avez-vous de fréres plus agés que vous'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='older_sisters',
            field=models.PositiveSmallIntegerField(verbose_name='Combien avez-vous de soeurs plus agés que vous'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='past_breast_cancer',
            field=models.BooleanField(verbose_name='Avez vous eu un cancer du sein'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='past_cancer',
            field=models.BooleanField(verbose_name='Avez vous eu un cancer'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='past_other_cancer',
            field=models.BooleanField(verbose_name='Avez-vous eu personnellement un des cancers suivants (Colon ou rectum, melanome, cerveau, estomac)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='psa',
            field=models.FloatField(verbose_name='Quel est votre taux de PSA (ng/ml)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='sexual_difficulties',
            field=models.BooleanField(verbose_name='Avez vous des difficultés sexuels (baisse de la libido ou des difficultés pour avoir des érections satisfaisantes)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='sister_prostate',
            field=models.PositiveSmallIntegerField(verbose_name='Combien de vos soeurs ont eu un cancer du sein'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='sisters',
            field=models.PositiveSmallIntegerField(verbose_name='Combien avez-vous de soeurs '),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='volume_prostate',
            field=models.FloatField(verbose_name='Quel est votre volume de prostate (cc mesuré en échographie)'),
        ),
        migrations.AlterField(
            model_name='person_inputs',
            name='weight',
            field=models.FloatField(verbose_name='Quels est votre Poids (kg)'),
        ),
        migrations.DeleteModel(
            name='Person_Results',
        ),
    ]
